/* HOP-02 — imported by scripts/import-inventory.mjs at ck-e7.
   Source: corpus/repos/holy-ops-v2/index.html:5144-5200
   The researcher's grade (B) and editorial_status
   (promising_exploration) live in `proposed_grade` — a proposal,
   never a ruling. Status is 'unsorted' until Julia rules. */
Shell.registerEntry({
  entity: 'exploration',
  id: 'hop-02',
  index: 'HOP-02',
  title: `Procedural certificate plate: ornamental double border with quadratic corner flourishes`,
  section: 'unfiled',
  status: 'unsorted',
  proposed_grade: 'B · promising_exploration',
  lane: 'canvas2d',
  tags: ['imported', 'unsorted'],
  source: {
    kind: 'reference-study',
    title: `corpus/repos/holy-ops-v2/index.html:5144-5200`,
    author: 'Julia Compton',
    note: `The sign-table mirror is the reusable idea (write the corner once, get four). The rest is decoration with no cause behind it - fine as an export artefact, not as a worked example.`
  },
  thumb: 'thumb.png',
  text: `<p>800x1100 canvas; two inset stroked rects, then four corner flourishes generated by mirroring one quadratic curve plus two ticks through a [dx,dy] sign table; Roman-numeral slot rows beneath.</p>
    <p><b>Note.</b> The sign-table mirror is the reusable idea (write the corner once, get four). The rest is decoration with no cause behind it - fine as an export artefact, not as a worked example.</p>
    <p class="cite" style="font-family:var(--f-mach);font-size:12px;color:var(--ink-3)">
      Source: <code>corpus/repos/holy-ops-v2/index.html:5144-5200</code> · Canvas2D · implementation-lane appendix
    </p>
    <p><b>Status: unsorted.</b> Imported from the corpus inventory at ck-e7. The researcher's proposed grade sits in the metadata as <code>proposed_grade</code>; it is a proposal, not a ruling (DECISION-FRAMING D5). Awaiting julia.</p>`
});
