/* atoms.js — GENERATED by scripts/build-crossover.mjs · ck-e13.
   Do not edit by hand; regenerate with `node scripts/build-crossover.mjs`.
   Fine-grained atom index: every technique block that names an atom in its atoms[] appears here. Distinct from the top-level entry.uses[] chain.
 */
Shell.registerCrossover("atoms", {
  "hairline": {
    "used_by": [
      {
        "technique_id": "hairline-construction",
        "entry_id": "birefringent-ray-bench",
        "plate": "A5"
      }
    ]
  },
  "construction": {
    "used_by": [
      {
        "technique_id": "hairline-construction",
        "entry_id": "birefringent-ray-bench",
        "plate": "A5"
      }
    ]
  },
  "glass": {
    "used_by": [
      {
        "technique_id": "glass-body",
        "entry_id": "birefringent-ray-bench",
        "plate": "A5"
      }
    ]
  },
  "filled-body": {
    "used_by": [
      {
        "technique_id": "glass-body",
        "entry_id": "birefringent-ray-bench",
        "plate": "A5"
      }
    ]
  },
  "transmission-hatch": {
    "used_by": [
      {
        "technique_id": "glass-body",
        "entry_id": "birefringent-ray-bench",
        "plate": "A5"
      }
    ]
  },
  "dash-encoding": {
    "used_by": [
      {
        "technique_id": "phase-key-ray",
        "entry_id": "birefringent-ray-bench",
        "plate": "A5"
      }
    ]
  },
  "weight-emphasis": {
    "used_by": [
      {
        "technique_id": "phase-key-ray",
        "entry_id": "birefringent-ray-bench",
        "plate": "A5"
      }
    ]
  },
  "angle-marker": {
    "used_by": [
      {
        "technique_id": "walk-off-geometry",
        "entry_id": "birefringent-ray-bench",
        "plate": "A5"
      }
    ]
  },
  "annotated-exaggeration": {
    "used_by": [
      {
        "technique_id": "walk-off-geometry",
        "entry_id": "birefringent-ray-bench",
        "plate": "A5"
      }
    ]
  },
  "dashed-extension": {
    "used_by": [
      {
        "technique_id": "dimension-band",
        "entry_id": "birefringent-ray-bench",
        "plate": "A5"
      }
    ]
  },
  "dimension-arrow": {
    "used_by": [
      {
        "technique_id": "dimension-band",
        "entry_id": "birefringent-ray-bench",
        "plate": "A5"
      }
    ]
  },
  "serif-italic-letter": {
    "used_by": [
      {
        "technique_id": "dimension-band",
        "entry_id": "birefringent-ray-bench",
        "plate": "A5"
      }
    ]
  },
  "state-glyph": {
    "used_by": [
      {
        "technique_id": "polarization-state-glyph",
        "entry_id": "birefringent-ray-bench",
        "plate": "A5"
      }
    ]
  },
  "mono-e-label": {
    "used_by": [
      {
        "technique_id": "polarization-state-glyph",
        "entry_id": "birefringent-ray-bench",
        "plate": "A5"
      }
    ]
  },
  "bottom-rule": {
    "used_by": [
      {
        "technique_id": "stage-rule-legend",
        "entry_id": "birefringent-ray-bench",
        "plate": "A5"
      }
    ]
  },
  "roman-stage-label": {
    "used_by": [
      {
        "technique_id": "stage-rule-legend",
        "entry_id": "birefringent-ray-bench",
        "plate": "A5"
      }
    ]
  }
});
