/* techniques.js — GENERATED by scripts/build-crossover.mjs · ck-e13.
   Do not edit by hand; regenerate with `node scripts/build-crossover.mjs`.
   Fine-grained technique index: every entry that names a technique id in its spec.techniques[] appears here. Distinct from the coarse instance_of[] and uses[] aggregations the shell already computes from the manifest.
 */
Shell.registerCrossover("techniques", {
  "hairline-construction": {
    "name": "Hairline construction",
    "layer": "GRAPHIC COMPOSITION",
    "appears_in": [
      {
        "entry_id": "birefringent-ray-bench",
        "plate": "A5",
        "params_keys": 3
      }
    ]
  },
  "glass-body": {
    "name": "Optical glass body",
    "layer": "GRAPHIC COMPOSITION",
    "appears_in": [
      {
        "entry_id": "birefringent-ray-bench",
        "plate": "A5",
        "params_keys": 8
      }
    ]
  },
  "phase-key-ray": {
    "name": "Phase-key ray",
    "layer": "GRAPHIC COMPOSITION",
    "appears_in": [
      {
        "entry_id": "birefringent-ray-bench",
        "plate": "A5",
        "params_keys": 5
      }
    ]
  },
  "walk-off-geometry": {
    "name": "Walk-off geometry",
    "layer": "STRUCTURE",
    "appears_in": [
      {
        "entry_id": "birefringent-ray-bench",
        "plate": "A5",
        "params_keys": 6
      }
    ]
  },
  "dimension-band": {
    "name": "Dimension band",
    "layer": "GRAPHIC COMPOSITION",
    "appears_in": [
      {
        "entry_id": "birefringent-ray-bench",
        "plate": "A5",
        "params_keys": 5
      }
    ]
  },
  "polarization-state-glyph": {
    "name": "Polarization-state glyph",
    "layer": "GRAPHIC COMPOSITION",
    "appears_in": [
      {
        "entry_id": "birefringent-ray-bench",
        "plate": "A5",
        "params_keys": 5
      }
    ]
  },
  "stage-rule-legend": {
    "name": "Stage-rule legend",
    "layer": "GRAPHIC COMPOSITION",
    "appears_in": [
      {
        "entry_id": "birefringent-ray-bench",
        "plate": "A5",
        "params_keys": 2
      }
    ]
  },
  "grain-fill": {
    "name": "Directional pencil grain",
    "layer": 2,
    "appears_in": [
      {
        "entry_id": "st-01-pencil-keyline-botanical",
        "plate": "ST-01",
        "params_keys": 12
      }
    ]
  },
  "keyline": {
    "name": "Contrast keyline",
    "layer": 5,
    "appears_in": [
      {
        "entry_id": "st-01-pencil-keyline-botanical",
        "plate": "ST-01",
        "params_keys": 12
      },
      {
        "entry_id": "st-03-thermal-chips",
        "plate": "ST-03",
        "params_keys": 12
      },
      {
        "entry_id": "st-04-chromolitho-calendar",
        "plate": "ST-04",
        "params_keys": 12
      }
    ]
  },
  "striation": {
    "name": "Radial striation",
    "layer": 3,
    "appears_in": [
      {
        "entry_id": "st-01-pencil-keyline-botanical",
        "plate": "ST-01",
        "params_keys": 9
      }
    ]
  },
  "fringe": {
    "name": "Dry-brush bristle fringe",
    "layer": 4,
    "appears_in": [
      {
        "entry_id": "st-01-pencil-keyline-botanical",
        "plate": "ST-01",
        "params_keys": 19
      }
    ]
  },
  "throat-glow": {
    "name": "Radial pencil ramp",
    "layer": 2,
    "appears_in": [
      {
        "entry_id": "st-01-pencil-keyline-botanical",
        "plate": "ST-01",
        "params_keys": 9
      }
    ]
  },
  "stamen": {
    "name": "Cream stamen with ring",
    "layer": 3,
    "appears_in": [
      {
        "entry_id": "st-01-pencil-keyline-botanical",
        "plate": "ST-01",
        "params_keys": 8
      }
    ]
  },
  "vein": {
    "name": "Olive petal vein",
    "layer": 3,
    "appears_in": [
      {
        "entry_id": "st-01-pencil-keyline-botanical",
        "plate": "ST-01",
        "params_keys": 6
      }
    ]
  },
  "stem-gradient": {
    "name": "Bristle stem gradient",
    "layer": 2,
    "appears_in": [
      {
        "entry_id": "st-01-pencil-keyline-botanical",
        "plate": "ST-01",
        "params_keys": 6
      }
    ]
  },
  "stem": {
    "name": "Ribbon stem",
    "layer": 1,
    "appears_in": [
      {
        "entry_id": "st-01-pencil-keyline-botanical",
        "plate": "ST-01",
        "params_keys": 6
      }
    ]
  },
  "mound": {
    "name": "Olive mound",
    "layer": 1,
    "appears_in": [
      {
        "entry_id": "st-01-pencil-keyline-botanical",
        "plate": "ST-01",
        "params_keys": 5
      }
    ]
  },
  "ray": {
    "name": "Outer ray (burr)",
    "layer": 3,
    "appears_in": [
      {
        "entry_id": "st-02-stipple-ray-bloom",
        "plate": "ST-02",
        "params_keys": 15
      }
    ]
  },
  "bowl": {
    "name": "Tilted bowl",
    "layer": 3,
    "appears_in": [
      {
        "entry_id": "st-02-stipple-ray-bloom",
        "plate": "ST-02",
        "params_keys": 11
      }
    ]
  },
  "rim": {
    "name": "Rim ellipse",
    "layer": 3,
    "appears_in": [
      {
        "entry_id": "st-02-stipple-ray-bloom",
        "plate": "ST-02",
        "params_keys": 8
      }
    ]
  },
  "inner-ray": {
    "name": "Bowl interior rays",
    "layer": 3,
    "appears_in": [
      {
        "entry_id": "st-02-stipple-ray-bloom",
        "plate": "ST-02",
        "params_keys": 8
      }
    ]
  },
  "corolla": {
    "name": "Corolla dot cloud",
    "layer": 2,
    "appears_in": [
      {
        "entry_id": "st-02-stipple-ray-bloom",
        "plate": "ST-02",
        "params_keys": 8
      }
    ]
  },
  "calyx": {
    "name": "Calyx funnel",
    "layer": 2,
    "appears_in": [
      {
        "entry_id": "st-02-stipple-ray-bloom",
        "plate": "ST-02",
        "params_keys": 7
      }
    ]
  },
  "leaf-screen": {
    "name": "Coarse dot screen",
    "layer": 1,
    "appears_in": [
      {
        "entry_id": "st-02-stipple-ray-bloom",
        "plate": "ST-02",
        "params_keys": 12
      }
    ]
  },
  "leaf-stipple": {
    "name": "Interior stipple",
    "layer": 1,
    "appears_in": [
      {
        "entry_id": "st-02-stipple-ray-bloom",
        "plate": "ST-02",
        "params_keys": 5
      }
    ]
  },
  "vine": {
    "name": "Dry-pen vine",
    "layer": 4,
    "appears_in": [
      {
        "entry_id": "st-02-stipple-ray-bloom",
        "plate": "ST-02",
        "params_keys": 10
      }
    ]
  },
  "ground": {
    "name": "Paper mottle",
    "layer": null,
    "appears_in": [
      {
        "entry_id": "st-02-stipple-ray-bloom",
        "plate": "ST-02",
        "params_keys": 5
      },
      {
        "entry_id": "st-03-thermal-chips",
        "plate": "ST-03",
        "params_keys": 3
      },
      {
        "entry_id": "st-07-massive-drawn-geometry",
        "plate": "ST-07",
        "params_keys": 2
      }
    ]
  },
  "thermal": {
    "name": "Warped thermal ramp",
    "layer": 2,
    "appears_in": [
      {
        "entry_id": "st-03-thermal-chips",
        "plate": "ST-03",
        "params_keys": 14
      }
    ]
  },
  "diecut": {
    "name": "Die-cut rings",
    "layer": 1,
    "appears_in": [
      {
        "entry_id": "st-03-thermal-chips",
        "plate": "ST-03",
        "params_keys": 4
      }
    ]
  },
  "flat-plate": {
    "name": "Flat plate",
    "layer": 2,
    "appears_in": [
      {
        "entry_id": "st-03-thermal-chips",
        "plate": "ST-03",
        "params_keys": 6
      },
      {
        "entry_id": "st-04-chromolitho-calendar",
        "plate": "ST-04",
        "params_keys": 3
      }
    ]
  },
  "cutout": {
    "name": "Cut window with pale rim",
    "layer": 3,
    "appears_in": [
      {
        "entry_id": "st-03-thermal-chips",
        "plate": "ST-03",
        "params_keys": 6
      }
    ]
  },
  "liquid-layer": {
    "name": "Liquid layer blob",
    "layer": 3,
    "appears_in": [
      {
        "entry_id": "st-03-thermal-chips",
        "plate": "ST-03",
        "params_keys": 3
      }
    ]
  },
  "grain": {
    "name": "Print grain",
    "layer": 5,
    "appears_in": [
      {
        "entry_id": "st-03-thermal-chips",
        "plate": "ST-03",
        "params_keys": 7
      }
    ]
  },
  "marbling": {
    "name": "Ridged marbling",
    "layer": 2,
    "appears_in": [
      {
        "entry_id": "st-03-thermal-chips",
        "plate": "ST-03",
        "params_keys": 4
      }
    ]
  },
  "dash-rows": {
    "name": "Dash-row micro text",
    "layer": 3,
    "appears_in": [
      {
        "entry_id": "st-03-thermal-chips",
        "plate": "ST-03",
        "params_keys": 8
      }
    ]
  },
  "misregister": {
    "name": "Plate register offset + knockout",
    "layer": 1,
    "appears_in": [
      {
        "entry_id": "st-04-chromolitho-calendar",
        "plate": "ST-04",
        "params_keys": 5
      }
    ]
  },
  "print-mottle": {
    "name": "Print mottle on inks",
    "layer": 8,
    "appears_in": [
      {
        "entry_id": "st-04-chromolitho-calendar",
        "plate": "ST-04",
        "params_keys": 5
      }
    ]
  },
  "scan-softness": {
    "name": "Scan softness",
    "layer": 10,
    "appears_in": [
      {
        "entry_id": "st-04-chromolitho-calendar",
        "plate": "ST-04",
        "params_keys": 4
      }
    ]
  },
  "tile-scallop": {
    "name": "Scallop (fish-scale) tile",
    "layer": 2,
    "appears_in": [
      {
        "entry_id": "st-04-chromolitho-calendar",
        "plate": "ST-04",
        "params_keys": 8
      }
    ]
  },
  "tile-spiral": {
    "name": "Spiral tile",
    "layer": 2,
    "appears_in": [
      {
        "entry_id": "st-04-chromolitho-calendar",
        "plate": "ST-04",
        "params_keys": 13
      }
    ]
  },
  "tile-squares": {
    "name": "Square-and-dot tile",
    "layer": 2,
    "appears_in": [
      {
        "entry_id": "st-04-chromolitho-calendar",
        "plate": "ST-04",
        "params_keys": 8
      }
    ]
  },
  "tile-hearts": {
    "name": "Heart tile",
    "layer": 2,
    "appears_in": [
      {
        "entry_id": "st-04-chromolitho-calendar",
        "plate": "ST-04",
        "params_keys": 8
      }
    ]
  },
  "tile-scroll": {
    "name": "Running-scroll band",
    "layer": 2,
    "appears_in": [
      {
        "entry_id": "st-04-chromolitho-calendar",
        "plate": "ST-04",
        "params_keys": 8
      }
    ]
  },
  "tile-wave": {
    "name": "Wave band",
    "layer": 2,
    "appears_in": [
      {
        "entry_id": "st-04-chromolitho-calendar",
        "plate": "ST-04",
        "params_keys": 9
      }
    ]
  },
  "dot-screen": {
    "name": "Salmon dot screen",
    "layer": 2,
    "appears_in": [
      {
        "entry_id": "st-04-chromolitho-calendar",
        "plate": "ST-04",
        "params_keys": 9
      }
    ]
  },
  "tile-zigzag": {
    "name": "Rust zigzag rule",
    "layer": 2,
    "appears_in": [
      {
        "entry_id": "st-04-chromolitho-calendar",
        "plate": "ST-04",
        "params_keys": 6
      }
    ]
  },
  "tile-checker": {
    "name": "Checker band",
    "layer": 2,
    "appears_in": [
      {
        "entry_id": "st-04-chromolitho-calendar",
        "plate": "ST-04",
        "params_keys": 3
      }
    ]
  },
  "tile-stars": {
    "name": "Star-sprig lunette",
    "layer": 2,
    "appears_in": [
      {
        "entry_id": "st-04-chromolitho-calendar",
        "plate": "ST-04",
        "params_keys": 6
      }
    ]
  },
  "arc": {
    "name": "Great arc",
    "layer": 3,
    "appears_in": [
      {
        "entry_id": "st-04-chromolitho-calendar",
        "plate": "ST-04",
        "params_keys": 5
      }
    ]
  },
  "botanical": {
    "name": "Keyline botanical",
    "layer": 4,
    "appears_in": [
      {
        "entry_id": "st-04-chromolitho-calendar",
        "plate": "ST-04",
        "params_keys": 4
      }
    ]
  },
  "hop-frieze": {
    "name": "Hop frieze",
    "layer": 4,
    "appears_in": [
      {
        "entry_id": "st-04-chromolitho-calendar",
        "plate": "ST-04",
        "params_keys": 6
      }
    ]
  },
  "cartouche": {
    "name": "Zodiac cartouche (Virgo)",
    "layer": 4,
    "appears_in": [
      {
        "entry_id": "st-04-chromolitho-calendar",
        "plate": "ST-04",
        "params_keys": 8
      }
    ]
  },
  "calendar-type": {
    "name": "Typeset calendar",
    "layer": 6,
    "appears_in": [
      {
        "entry_id": "st-04-chromolitho-calendar",
        "plate": "ST-04",
        "params_keys": 6
      }
    ]
  },
  "paper": {
    "name": "Cream paper",
    "layer": null,
    "appears_in": [
      {
        "entry_id": "st-04-chromolitho-calendar",
        "plate": "ST-04",
        "params_keys": 4
      },
      {
        "entry_id": "st-08-two-ink-saint",
        "plate": "ST-08",
        "params_keys": 4
      }
    ]
  },
  "contour": {
    "name": "Brush-ink contour",
    "layer": 4,
    "appears_in": [
      {
        "entry_id": "st-05-isometric-stipple-facade",
        "plate": "ST-05",
        "params_keys": 18
      }
    ]
  },
  "stipple-cylinder": {
    "name": "Fluted-shaft stipple",
    "layer": 3,
    "appears_in": [
      {
        "entry_id": "st-05-isometric-stipple-facade",
        "plate": "ST-05",
        "params_keys": 14
      }
    ]
  },
  "stipple-field": {
    "name": "Half-lit front field",
    "layer": 3,
    "appears_in": [
      {
        "entry_id": "st-05-isometric-stipple-facade",
        "plate": "ST-05",
        "params_keys": 11
      }
    ]
  },
  "flat-fill": {
    "name": "Flat ink face",
    "layer": 1,
    "appears_in": [
      {
        "entry_id": "st-05-isometric-stipple-facade",
        "plate": "ST-05",
        "params_keys": 4
      }
    ]
  },
  "yellow-return": {
    "name": "Stippled yellow return",
    "layer": 3,
    "appears_in": [
      {
        "entry_id": "st-05-isometric-stipple-facade",
        "plate": "ST-05",
        "params_keys": 8
      }
    ]
  },
  "projection": {
    "name": "Near-frontal dimetric",
    "layer": null,
    "appears_in": [
      {
        "entry_id": "st-05-isometric-stipple-facade",
        "plate": "ST-05",
        "params_keys": 9
      }
    ]
  },
  "palette": {
    "name": "Four-ink colour system",
    "layer": 1,
    "appears_in": [
      {
        "entry_id": "st-05-isometric-stipple-facade",
        "plate": "ST-05",
        "params_keys": 7
      }
    ]
  },
  "baluster": {
    "name": "Turned baluster",
    "layer": 2,
    "appears_in": [
      {
        "entry_id": "st-05-isometric-stipple-facade",
        "plate": "ST-05",
        "params_keys": 12
      }
    ]
  },
  "floor-grid": {
    "name": "Pink tile floor",
    "layer": 1,
    "appears_in": [
      {
        "entry_id": "st-05-isometric-stipple-facade",
        "plate": "ST-05",
        "params_keys": 8
      }
    ]
  },
  "rustication": {
    "name": "Rusticated base",
    "layer": 2,
    "appears_in": [
      {
        "entry_id": "st-05-isometric-stipple-facade",
        "plate": "ST-05",
        "params_keys": 12
      }
    ]
  },
  "luma": {
    "name": "Luminance, stretched + local contrast",
    "layer": "source",
    "appears_in": [
      {
        "entry_id": "st-06-massive-source-instrument",
        "plate": "ST-06",
        "params_keys": 5
      }
    ]
  },
  "mask": {
    "name": "Background mask",
    "layer": "source",
    "appears_in": [
      {
        "entry_id": "st-06-massive-source-instrument",
        "plate": "ST-06",
        "params_keys": 4
      }
    ]
  },
  "etf": {
    "name": "Edge tangent flow (Kang 2007)",
    "layer": "field",
    "appears_in": [
      {
        "entry_id": "st-06-massive-source-instrument",
        "plate": "ST-06",
        "params_keys": 6
      }
    ]
  },
  "structure": {
    "name": "Hand-set structure",
    "layer": "key",
    "appears_in": [
      {
        "entry_id": "st-06-massive-source-instrument",
        "plate": "ST-06",
        "params_keys": 6
      }
    ]
  },
  "fdog-key": {
    "name": "Flow-based DoG key with NMS",
    "layer": "key",
    "appears_in": [
      {
        "entry_id": "st-06-massive-source-instrument",
        "plate": "ST-06",
        "params_keys": 18
      }
    ]
  },
  "darkkey-marquee": {
    "name": "Medial-axis key · marquee lettering",
    "layer": "key",
    "appears_in": [
      {
        "entry_id": "st-06-massive-source-instrument",
        "plate": "ST-06",
        "params_keys": 14
      }
    ]
  },
  "darkkey-screen": {
    "name": "Medial-axis key · screen content",
    "layer": "key",
    "appears_in": [
      {
        "entry_id": "st-06-massive-source-instrument",
        "plate": "ST-06",
        "params_keys": 12
      }
    ]
  },
  "hatch": {
    "name": "Streamline hatch on the flow",
    "layer": "hatch",
    "appears_in": [
      {
        "entry_id": "st-06-massive-source-instrument",
        "plate": "ST-06",
        "params_keys": 18
      }
    ]
  },
  "spot-plate": {
    "name": "Vector spot plate, knocked out, off register",
    "layer": "spot",
    "appears_in": [
      {
        "entry_id": "st-06-massive-source-instrument",
        "plate": "ST-06",
        "params_keys": 13
      },
      {
        "entry_id": "st-07-massive-drawn-geometry",
        "plate": "ST-07",
        "params_keys": 12
      }
    ]
  },
  "composite": {
    "name": "Plate compositing",
    "layer": "composite",
    "appears_in": [
      {
        "entry_id": "st-06-massive-source-instrument",
        "plate": "ST-06",
        "params_keys": 5
      }
    ]
  },
  "keyline-structure": {
    "name": "Structure key (ribbons)",
    "layer": 3,
    "appears_in": [
      {
        "entry_id": "st-07-massive-drawn-geometry",
        "plate": "ST-07",
        "params_keys": 9
      }
    ]
  },
  "keyline-chains": {
    "name": "Detail key · broken chains",
    "layer": 3,
    "appears_in": [
      {
        "entry_id": "st-07-massive-drawn-geometry",
        "plate": "ST-07",
        "params_keys": 8
      }
    ]
  },
  "hatch-streamlines": {
    "name": "Tone-driven streamline hatch",
    "layer": 2,
    "appears_in": [
      {
        "entry_id": "st-07-massive-drawn-geometry",
        "plate": "ST-07",
        "params_keys": 16
      }
    ]
  },
  "ground-tick": {
    "name": "Base tick",
    "layer": 2,
    "appears_in": [
      {
        "entry_id": "st-07-massive-drawn-geometry",
        "plate": "ST-07",
        "params_keys": 6
      }
    ]
  },
  "knockout": {
    "name": "Stepped white masses",
    "layer": 1,
    "appears_in": [
      {
        "entry_id": "st-07-massive-drawn-geometry",
        "plate": "ST-07",
        "params_keys": 8
      }
    ]
  },
  "screen-ink": {
    "name": "Screen ink lattice",
    "layer": 1,
    "appears_in": [
      {
        "entry_id": "st-07-massive-drawn-geometry",
        "plate": "ST-07",
        "params_keys": 20
      }
    ]
  },
  "marquee-outline": {
    "name": "MASSIVE mass outline",
    "layer": 3,
    "appears_in": [
      {
        "entry_id": "st-07-massive-drawn-geometry",
        "plate": "ST-07",
        "params_keys": 13
      }
    ]
  },
  "controls": {
    "name": "Panel controls",
    "layer": 3,
    "appears_in": [
      {
        "entry_id": "st-07-massive-drawn-geometry",
        "plate": "ST-07",
        "params_keys": 7
      }
    ]
  },
  "monoline": {
    "name": "Organic monoline pen",
    "layer": 1,
    "appears_in": [
      {
        "entry_id": "st-08-two-ink-saint",
        "plate": "ST-08",
        "params_keys": 12
      }
    ]
  },
  "two-ink": {
    "name": "Two inks, one job each",
    "layer": 1,
    "appears_in": [
      {
        "entry_id": "st-08-two-ink-saint",
        "plate": "ST-08",
        "params_keys": 6
      }
    ]
  },
  "cord": {
    "name": "Root-cords with growths",
    "layer": 1,
    "appears_in": [
      {
        "entry_id": "st-08-two-ink-saint",
        "plate": "ST-08",
        "params_keys": 8
      }
    ]
  },
  "fold": {
    "name": "Shroud folds",
    "layer": 1,
    "appears_in": [
      {
        "entry_id": "st-08-two-ink-saint",
        "plate": "ST-08",
        "params_keys": 4
      }
    ]
  },
  "halo-dots": {
    "name": "Stippled corona",
    "layer": 1,
    "appears_in": [
      {
        "entry_id": "st-08-two-ink-saint",
        "plate": "ST-08",
        "params_keys": 6
      }
    ]
  },
  "lattice": {
    "name": "Girdle lattice",
    "layer": 2,
    "appears_in": [
      {
        "entry_id": "st-08-two-ink-saint",
        "plate": "ST-08",
        "params_keys": 6
      }
    ]
  },
  "star-column": {
    "name": "Spine and stars",
    "layer": 2,
    "appears_in": [
      {
        "entry_id": "st-08-two-ink-saint",
        "plate": "ST-08",
        "params_keys": 3
      }
    ]
  },
  "ribs": {
    "name": "Uneven ribs",
    "layer": 2,
    "appears_in": [
      {
        "entry_id": "st-08-two-ink-saint",
        "plate": "ST-08",
        "params_keys": 5
      }
    ]
  },
  "hands": {
    "name": "Long hands",
    "layer": 1,
    "appears_in": [
      {
        "entry_id": "st-08-two-ink-saint",
        "plate": "ST-08",
        "params_keys": 6
      }
    ]
  },
  "legs-feet": {
    "name": "Cord legs and small feet",
    "layer": 1,
    "appears_in": [
      {
        "entry_id": "st-08-two-ink-saint",
        "plate": "ST-08",
        "params_keys": 4
      }
    ]
  }
});
