/* Techniques & Templates · manifest · ø co.
   One entry per study. Pages, the index and the related block all read this file.
   To add an entry: make a folder under techniques/ or templates/ with study.js (+ ref.png, thumb.png),
   add it here, run `node _build/build.mjs`. */
window.TT = {
  title: 'Techniques & Templates',
  mark: '<svg class="o" viewBox="0 0 256 256" aria-hidden="true"><g transform="translate(-554.33,-11.46)" fill="currentColor" fill-rule="evenodd"><path d="M682.33,35.81c-57.24,0-103.65,46.4-103.65,103.65s46.4,103.65,103.65,103.65,103.65-46.4,103.65-103.65-46.4-103.65-103.65-103.65ZM682.33,187.75c-26.67,0-48.29-21.62-48.29-48.29s21.62-48.29,48.29-48.29,48.29,21.62,48.29,48.29-21.62,48.29-48.29,48.29Z"/><rect x="666.18" y="-5.46" width="32.29" height="289.83" transform="translate(298.46 -441.63) rotate(45)"/></g></svg>',
  sections: [
    { id:'techniques', title:'Techniques', blurb:'One reference, one technique, one rebuild. Each plate measures the source, rebuilds it in code on an original subject, and files the numbers as a spec.' },
    { id:'templates',  title:'Templates',  blurb:'Composed layouts on the same shell — briefs, specs, sheets, decks.' }
  ],
  entries: [
    { id:'ts-01-moire-ring-screens', section:'techniques', code:'TS-01', path:'techniques/ts-01-moire-ring-screens/', title:'Moiré from two ring screens', sub:'Two concentric-ring gratings multiplied, dithered with grain, one hot core.', techniques:['ring-screen','moire-product','radial-heat','stochastic-grain','paper-margin'], variants:[['#E0402D','#5287BB','#F0EBE7'],['#F4551E','#2F5AE6','#FFFFFF'],['#101014','#B4B2AC','#FFFFFF']] },
    { id:'ts-02-four-ink-spot-illustration', section:'techniques', code:'TS-02', path:'techniques/ts-02-four-ink-spot-illustration/', title:'Four-ink spot illustration', sub:'Flat spot fills, a black keyline, hatched shading, slipped register, cream stock.', techniques:['spot-fill','black-keyline','hatch-shade','misregister','dot-tint','aged-stock','caption-label'], variants:[['#E0614F','#EDDC4D','#6599C8','#F7EDE3'],['#F4551E','#2F5AE6','#101014','#FFFFFF'],['#2F5AE6','#101014','#FFFFFF']] },
    { id:'ts-03-iridescent-chrome', section:'techniques', code:'TS-03', path:'techniques/ts-03-iridescent-chrome/', title:'Iridescent chrome on black', sub:'A bent slab shaded by a spectral gradient across its normals, film grain, split-channel wordmarks.', techniques:['spectral-lut','normal-shading','edge-highlight','film-grain','channel-split-type','display-headline'], variants:[['#0D0E0E','#386EB2','#6EC7D1','#E3D672'],['#101014','#F4551E','#2F5AE6','#FFFFFF'],['#0D0E0E','#EAECEC','#8A8A8A']] },
    { id:'ts-04-stacked-card-scroll', section:'techniques', code:'TS-04', path:'techniques/ts-04-stacked-card-scroll/', title:'Stacked card scroll', sub:'Rounded cards that pin and stack as the page scrolls; each card a different ground.', techniques:['sticky-stack','card-ground','rounded-frame','specimen-grid','soft-blur-plate'], variants:[['#C9382E','#DBDBFB','#B8B5B7'],['#F4551E','#FFFFFF','#101014'],['#101014','#F6F5F2','#E7E4DD']], live:true },
    { id:'ts-05-line-screen-type', section:'techniques', code:'TS-05', path:'techniques/ts-05-line-screen-type/', title:'Vertical line-screen type', sub:'Heavy serif type printed through a vertical line screen; line width follows a phase field.', techniques:['line-screen','phase-field','ink-bleed','paper-tooth','caption-label'], variants:[['#514D4A','#E5E1DB'],['#F4551E','#FFFFFF'],['#FFFFFF','#101014']] },
    { id:'ts-06-riso-plate-separation', section:'techniques', code:'TS-06', path:'techniques/ts-06-riso-plate-separation/', title:'Riso three-plate separation', sub:'Yellow, blue and fluorescent pink plates on an isometric drawing; each plate mis-registers and grains on its own.', techniques:['plate-separation','misregister','ink-grain','iso-extrude','marbled-fill','grid-stock'], variants:[['#E9E566','#614C90','#D859A3'],['#E9E566'],['#614C90'],['#D859A3'],['#F4551E','#2F5AE6','#101014']], motion:true },
    { id:'ts-07-gradient-map-blur-type', section:'techniques', code:'TS-07', path:'techniques/ts-07-gradient-map-blur-type/', title:'Gradient-mapped blur type', sub:'Heavy type and a blob field blurred together, then mapped through a four-stop ramp; the blur breathes.', techniques:['blur-field','gradient-map','blob-field','display-stack','breath-motion'], variants:[['#101014','#F5391E','#F6C9DA','#E9E9E9'],['#101014','#F4551E','#FFFFFF'],['#101014','#2F5AE6','#FFFFFF']], motion:true },
    { id:'ts-08-flat-color-card-set', section:'techniques', code:'TS-08', path:'techniques/ts-08-flat-color-card-set/', title:'Flat-color card set', sub:'Six rounded cards, one flat color each, condensed display type at two scales, mono metadata at the edges.', techniques:['card-ground','rounded-frame','condensed-display','edge-metadata','gradient-plate','rule-ledger'], variants:[['#E2412C','#EFD32C','#1E9A55','#B9E6D6','#2A2ED8'],['#F4551E','#2F5AE6','#101014','#FFFFFF','#F6F5F2'],['#101014','#FFFFFF']], live:true },
    { id:'ts-09-grain-gradient-layers', section:'techniques', code:'TS-09', path:'techniques/ts-09-grain-gradient-layers/', title:'Grain gradient layers', sub:'Soft-edged shapes over two-stop gradients, a rippled band, and one film grain over everything.', techniques:['soft-mask','two-stop-gradient','ripple-band','film-grain','caption-label'], variants:[['#F26A1B','#E4243B','#1F8FE0','#101014'],['#F4551E','#2F5AE6','#FFFFFF','#101014'],['#101014','#B4B2AC','#FFFFFF']] },
    { id:'ts-10-thermal-blob-field', section:'techniques', code:'TS-10', path:'techniques/ts-10-thermal-blob-field/', title:'Thermal blob field', sub:'A blurred blob field mapped through a ramp with a dark rim stop, on paper with tooth.', techniques:['blob-field','gradient-map','rim-stop','paper-tooth','rule-ledger'], variants:[['#F7EFE0','#F08A1C','#1B2A5B'],['#F7EFE0','#1F7A8C','#F3C623','#0F2A1E'],['#F7EFE0','#FF5FA8','#F0451E','#101014'],['#FFFFFF','#F4551E','#2F5AE6']], motion:true },
    { id:'ts-11-worn-black-box', section:'techniques', code:'TS-11', path:'techniques/ts-11-worn-black-box/', title:'Worn black box', sub:'A black board box, front and back, with edge scuff, creases, a cream flap, stickers and a barcode block.', techniques:['board-panel','edge-scuff','crease-line','sticker-layer','barcode-block','edge-metadata'], variants:[['#111111','#D9D0B8','#F08A1C'],['#101014','#FFFFFF','#F4551E'],['#F6F5F2','#101014','#2F5AE6']] },
    { id:'ts-12-perforated-stamp', section:'techniques', code:'TS-12', path:'techniques/ts-12-perforated-stamp/', title:'Perforated stamp', sub:'A red stamp with a scalloped perforation, a halftoned serif title running up the edge, and a script credit.', techniques:['perforation','halftone-fill','rotated-display','script-credit','paper-tooth'], variants:[['#E8241B','#2A2118','#FFFFFF'],['#F4551E','#101014','#FFFFFF'],['#2F5AE6','#101014','#FFFFFF']] },
    { id:'ts-13-glyph-field-animation', section:'techniques', code:'TS-13', path:'techniques/ts-13-glyph-field-animation/', title:'ASCII glyph-field animations', sub:'Monospace glyphs as particles — a projected helix with palette labels, a sine wave grid, a breathing orbit and a pulse row, all fillText.', techniques:['glyph-helix','depth-alpha','semantic-label','glyph-vocab','center-mask','pointer-parallax','wave-grid','pulse-row','orbit-ring','still-frame-runtime'], variants:[['#09090B','#F6F1E4','#10B981','#2B8EF5'],['#101014','#F4551E','#2F5AE6','#FFFFFF'],['#FFFFFF','#101014','#10B981','#2B8EF5']], motion:true, live:true },
    { id:'t-01-project-brief', section:'templates', code:'T-01', path:'templates/t-01-project-brief/', title:'Project brief', sub:'A one-page project brief on the shell — premise, mandate, territories, deliverables, measures.', techniques:[], variants:[['#F4551E','#2F5AE6','#101014','#FFFFFF']] },
    { id:'t-02-editorial-spec-ascii', section:'templates', code:'T-02', path:'templates/t-02-editorial-spec-ascii/', title:'Editorial spec w/ ASCII animations', sub:'A component library set as an editorial specimen — serif display, mono chrome, hairline plates on white, ink as punctuation, and four glyph-field canvas animations (TS-13).', techniques:[], variants:[['#09090B','#F6F1E4','#10B981','#2B8EF5']] }
  ]
};
